### ISSUE TITLE
Package use with visual Studio

### ISSUE THREAD

**Issue by yrzhanov** [mppmu/qmc#2]
Hello,
to use GPU support you compile programs with nvcc. I have an existing Visual Studio project that I would like to speed up using your package. I was able to create a solution containing your tests and examples. They run correctly. However, I'm not sure that they are using GPU as nvcc is not invoked while building. Even when the new project is added as CUDA runtime and the project contains CUDA includes and libraries. During the execution of a compiled program I don't see significant use of GPUs. Can you advise what should be done to make sure that the integrator runs on GPUs?
Thank you,
    Yuri

**Comment by spj101** [comment]
Perhaps the simplest way is to increase the verbosity is to add the line in any example file:
```integrator.verbosity = 1;```

When the code is running you should see a list of devices:
```[891 ms] devices -1 0 1 2 3```

Here device -1 is the CPU, 0 is the first gpu, 1 is the second gpu and so on.
You can select which devices the code runs on with, e.g.:
```integrator.devices = {0,1,2};```

You should also see messages indicating how many device threads are being set:
```[891 ms] creating 72 cputhreads,4 non-cpu threads```
Here 4 non-cpu threads means that 4 GPUs have been detected.

Finally in the lines with `(#)` the # indicates which device the lines refer to, for example:
```
[947 ms] (0) Million Function Evaluations/s: 7.45095 Mfeps (Approx)
[947 ms] (1) Million Function Evaluations/s: 0 Mfeps (Approx)
[947 ms] (2) Million Function Evaluations/s: 0 Mfeps (Approx)
[947 ms] (3) Million Function Evaluations/s: 0 Mfeps (Approx)
```
would indicate that the first GPU computed all points whilst the others sat idle.

To see good GPU utilisation you may want to increase the number of points requested (`minn`). It could be that for most examples your CPU computes all points before the GPUs have even finished copying the function to device memory.

**Comment by yrzhanov** [comment]
Thank you - that's very clear. One more question: how to pass thread-specific data to the integrand? I need to calculate thousands of integrals, each with it's own set of constants.
Cheers,
    Yuri

**Comment by spj101** [comment]
I would not advise passing thread-specific data to the integrand. If you want to simultaneously compute different integrals then create several threads (in the C++ sense) and in each thread have a different instance of the qmc integrator. You can control the number of cpu threads each qmc integrator wants to use with the `cputhreads` variable. There is no advantage to doing over computing the integrals sequentially with a single instance of the qmc unless your integrals are really extremely simple.

I suspect you may instead want to define an integral that depends on some parameter(s). You then want to know this integral for several values of this parameter. If this is the case then there are a few ways to do this depending on exactly what you need. Since you are passing a functor to the integrator you can add parameters to your functor and set them as you need prior to handing them to the qmc. 

For example:
```cpp
struct my_functor_t {
    const unsigned long long int number_of_integration_variables = 3;
    double parameter = 0; // <--- new parameter
#ifdef __CUDACC__
    __host__ __device__
#endif
    double operator()(double* x) const
    {
        return parameter*x[0]*x[1]*x[2];
    }
} my_functor;

int main() {

    const unsigned int MAXVAR = 3;

    integrators::Qmc<double,double,MAXVAR,integrators::transforms::Korobov<3>::type> integrator;

    // First integral
    my_functor.parameter=2.; // <--- set parameter
    integrators::result<double> result = integrator.integrate(my_functor);
    std::cout << "integral = " << result.integral << std::endl;
    std::cout << "error    = " << result.error    << std::endl;

    // Second Integral
    my_functor.parameter=3.; // <--- set parameter to a different value
    result = integrator.integrate(my_functor);
    std::cout << "integral = " << result.integral << std::endl;
    std::cout << "error    = " << result.error    << std::endl;

    return 0;
}
```

If you want something more fancy than a parameter, e.g. a function pointer, then take a look at the example `7_cuba_pointers_demo.cpp`.

**Comment by yrzhanov** [comment]
Got it - thank you.
Is there a way to specify integration limits explicitly, or it always happens over a hypercube and thus requires substitution of variables?

**Comment by spj101** [comment]
The integration is always over the unit hypercube. 

The transformation you are looking for is given e.g. at the bottom of the [Cuba page](http://www.feynarts.de/cuba/).
